### ISSUE TITLE
Rename the file and class names according to the naming convention 

### ISSUE THREAD

**Issue by Hanqi-Angelina** [CSC207-UofT/course-project-utalk#16]
Hello everyone, 

I was wondering whether you have time today to rename our classes and files names according to the naming convention for the new version of our code. 

If possible, please add TODOs to where you think more documentation is needed. 

Thanks.

**Comment by Hanqi-Angelina** [comment]
Feel free to add yourself to the assignee if you are able to do so.

**Comment by FrankQQQQ** [comment]
Hi

**Comment by Hanqi-Angelina** [comment]
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html
Please refer to this page for naming conventions

**Comment by Hanqi-Angelina** [comment]
Please make sure all your classes and methods adhere to the naming conventions

**Comment by Hanqi-Angelina** [comment]
Jiang Kuang fixed this part.
